version: "3.8"

services:
  prod-noodle:
    image: "ghcr.io/towerful/crestron:prod"
    restart: unless-stopped
    ports:
      - "8084:3000"
    environment:
      PORT: 3000
      CRESTRON_HOST: 10.10.10.90
      CRESTRON_USER: admin
      CRESTRON_PWD: admin